baseurl = "https://ldc-commenting.firebaseapp.com"
languageCode = "en-us"
title = "AURA Code Commenting"
author = "Kevin McLaughlin"
copyright = "Copyright (c) 2019, Kevin McLaughlin; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-bootstrap"

[params]
  mainSections = ["comments"]

disqusShortname = "xxxxxx"
googleAnalytics = "UA-XXXXXXX-1"

[[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags'></i>"
    weight = -110
    identifier = "tags"
    url = "/tags/"

[[menu.main]]
    name = "Categories"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = -100
    identifier = "categories"
    url = "/categories/"

[[menu.main]]
    name = "How To"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = -90
    identifier = "about-me"
    url = "/about"

[[menu.main]]
    name = "Code Draft"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = -90
    identifier = "plain-code"
    url = "/pdf/plain-code.pdf"

[[menu.main]]
    name = "Code Draft w Annotations"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = -90
    identifier = "annotatoted-code"
    url = "/pdf/annotated-code.pdf"


# You can have link at the footer as below
# [[menu.footer]]
#     name = "DISCLAIMER"
#     weight = -110
#     identifier = "disclaimer"
#     url = "/page/disclaimer/"
# 
# [[menu.footer]]
#     name = "LICENSE"
#     weight = -120
#     identifier = "license"
#     url = "/page/license/"
#


[taxonomies]
  category = "categories"
  chapter = "chapter"
  article = "article"
  division = "division"
  page = "page"
  tag = "tags"